#setup self ca
#this playbook required ansible 2.4 or later
---
- hosts: ca_host
  gather_facts: false
  become: true

  tasks:
    - name: ensure openssl installed
      package:
        name: openssl, python
        state: latest

    - name: ensure pip installed
      shell: which pip
      failed_when: result.rc < 0
      register: result

    - block:
      - name: download get-pip.py
        get_url:
          dest: ~/get-pip.py
          url: https://bootstrap.pypa.io/get-pip.py
      - name: install pip
        shell: python ~/get-pip.py
      when: result.rc == 1

    - name: ensure pyOpenSSL installed
      pip:
        name: pyOpenSSL
        state: present

    - name: ensure created selfca private key
      openssl_privatekey:
        path: /etc/pki/CA/private/cakey.pem
        state: present

    - name: ensure created csr
      openssl_csr:
        commonName: "{{ ca_CN }}"
        countryName: "{{ ca_C }}"
        emailAddress: "{{ ca_EMail }}"
        localityName: "{{ ca_L }}"
        organizationName: "{{ ca_O }}"
        organizationalUnitName: "{{ ca_OU }}"
        path: /etc/pki/CA/cacert.csr
        privatekey_path: /etc/pki/CA/private/cakey.pem
        state: present
        stateOrProvinceName: "{{ ca_ST }}"

    - name: ensure self sighed certificate
      openssl_certificate:
        csr_path: /etc/pki/CA/cacert.csr
        path: /etc/pki/CA/cacert.pem
        privatekey_path: /etc/pki/CA/private/cakey.pem
        provider: selfsigned
        state: present
        valid_in: 315360000

    - name: ensure CA cert convert to DER for client
      shell: openssl x509 -inform PEM -outform DER -in /etc/pki/CA/cacert.pem -out /etc/pki/CA/MyCAcert.der
      args:
        creates: /etc/pki/CA/MyCAcert.der

    - name: ensure index file created
      file:
        path: /etc/pki/CA/index.txt
        state: touch

    - name: ensure serial file created
      shell: echo "01" > /etc/pki/CA/serial
      args:
        creates: /etc/pki/CA/serial

    - name: ensure download CA cert
      fetch:
        dest: "{{ local_store_dir }}/MyCAcert.der"
        fail_on_missing: yes
        flat: yes
        src: "/etc/pki/CA/MyCAcert.der"
