---
#commonName
ca_CN: myCA.hogehoge.hoge

#countryName
ca_C: JP

#emailAddress
ca_EMail: hogehoge@hogehoge.hoge

#localityName
ca_L: Shinagawa

#organizationName
ca_O: my company

#organizationalUnitName
ca_OU: my division

#stateOrProvinceName
ca_ST: Tokyo
